//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace WebService {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WeatherWebServiceSoap", Namespace="http://WebXml.com.cn/")]
    public partial class WeatherWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getSupportCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupportProvinceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupportDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWeatherbyCityNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWeatherbyCityNameProOperationCompleted;
        
        /// <remarks/>
        public WeatherWebService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["EndpointURL"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://www.webxml.com.cn/WebServices/WeatherWebService.asmx";
            }
        }
        
        /// <remarks/>
        public event getSupportCityCompletedEventHandler getSupportCityCompleted;
        
        /// <remarks/>
        public event getSupportProvinceCompletedEventHandler getSupportProvinceCompleted;
        
        /// <remarks/>
        public event getSupportDataSetCompletedEventHandler getSupportDataSetCompleted;
        
        /// <remarks/>
        public event getWeatherbyCityNameCompletedEventHandler getWeatherbyCityNameCompleted;
        
        /// <remarks/>
        public event getWeatherbyCityNameProCompletedEventHandler getWeatherbyCityNameProCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getSupportCity", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getSupportCity(string byProvinceName) {
            object[] results = this.Invoke("getSupportCity", new object[] {
                        byProvinceName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSupportCity(string byProvinceName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSupportCity", new object[] {
                        byProvinceName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSupportCity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getSupportCityAsync(string byProvinceName) {
            this.getSupportCityAsync(byProvinceName, null);
        }
        
        /// <remarks/>
        public void getSupportCityAsync(string byProvinceName, object userState) {
            if ((this.getSupportCityOperationCompleted == null)) {
                this.getSupportCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportCityOperationCompleted);
            }
            this.InvokeAsync("getSupportCity", new object[] {
                        byProvinceName}, this.getSupportCityOperationCompleted, userState);
        }
        
        private void OngetSupportCityOperationCompleted(object arg) {
            if ((this.getSupportCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportCityCompleted(this, new getSupportCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getSupportProvince", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getSupportProvince() {
            object[] results = this.Invoke("getSupportProvince", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSupportProvince(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSupportProvince", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSupportProvince(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getSupportProvinceAsync() {
            this.getSupportProvinceAsync(null);
        }
        
        /// <remarks/>
        public void getSupportProvinceAsync(object userState) {
            if ((this.getSupportProvinceOperationCompleted == null)) {
                this.getSupportProvinceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportProvinceOperationCompleted);
            }
            this.InvokeAsync("getSupportProvince", new object[0], this.getSupportProvinceOperationCompleted, userState);
        }
        
        private void OngetSupportProvinceOperationCompleted(object arg) {
            if ((this.getSupportProvinceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportProvinceCompleted(this, new getSupportProvinceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getSupportDataSet", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSupportDataSet() {
            object[] results = this.Invoke("getSupportDataSet", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSupportDataSet(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSupportDataSet", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetSupportDataSet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getSupportDataSetAsync() {
            this.getSupportDataSetAsync(null);
        }
        
        /// <remarks/>
        public void getSupportDataSetAsync(object userState) {
            if ((this.getSupportDataSetOperationCompleted == null)) {
                this.getSupportDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportDataSetOperationCompleted);
            }
            this.InvokeAsync("getSupportDataSet", new object[0], this.getSupportDataSetOperationCompleted, userState);
        }
        
        private void OngetSupportDataSetOperationCompleted(object arg) {
            if ((this.getSupportDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportDataSetCompleted(this, new getSupportDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getWeatherbyCityName", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getWeatherbyCityName(string theCityName) {
            object[] results = this.Invoke("getWeatherbyCityName", new object[] {
                        theCityName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetWeatherbyCityName(string theCityName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWeatherbyCityName", new object[] {
                        theCityName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetWeatherbyCityName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getWeatherbyCityNameAsync(string theCityName) {
            this.getWeatherbyCityNameAsync(theCityName, null);
        }
        
        /// <remarks/>
        public void getWeatherbyCityNameAsync(string theCityName, object userState) {
            if ((this.getWeatherbyCityNameOperationCompleted == null)) {
                this.getWeatherbyCityNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWeatherbyCityNameOperationCompleted);
            }
            this.InvokeAsync("getWeatherbyCityName", new object[] {
                        theCityName}, this.getWeatherbyCityNameOperationCompleted, userState);
        }
        
        private void OngetWeatherbyCityNameOperationCompleted(object arg) {
            if ((this.getWeatherbyCityNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWeatherbyCityNameCompleted(this, new getWeatherbyCityNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getWeatherbyCityNamePro", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            object[] results = this.Invoke("getWeatherbyCityNamePro", new object[] {
                        theCityName,
                        theUserID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetWeatherbyCityNamePro(string theCityName, string theUserID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWeatherbyCityNamePro", new object[] {
                        theCityName,
                        theUserID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetWeatherbyCityNamePro(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getWeatherbyCityNameProAsync(string theCityName, string theUserID) {
            this.getWeatherbyCityNameProAsync(theCityName, theUserID, null);
        }
        
        /// <remarks/>
        public void getWeatherbyCityNameProAsync(string theCityName, string theUserID, object userState) {
            if ((this.getWeatherbyCityNameProOperationCompleted == null)) {
                this.getWeatherbyCityNameProOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWeatherbyCityNameProOperationCompleted);
            }
            this.InvokeAsync("getWeatherbyCityNamePro", new object[] {
                        theCityName,
                        theUserID}, this.getWeatherbyCityNameProOperationCompleted, userState);
        }
        
        private void OngetWeatherbyCityNameProOperationCompleted(object arg) {
            if ((this.getWeatherbyCityNameProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWeatherbyCityNameProCompleted(this, new getWeatherbyCityNameProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getSupportCityCompletedEventHandler(object sender, getSupportCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getSupportProvinceCompletedEventHandler(object sender, getSupportProvinceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportProvinceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportProvinceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getSupportDataSetCompletedEventHandler(object sender, getSupportDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getWeatherbyCityNameCompletedEventHandler(object sender, getWeatherbyCityNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWeatherbyCityNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWeatherbyCityNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getWeatherbyCityNameProCompletedEventHandler(object sender, getWeatherbyCityNameProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWeatherbyCityNameProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWeatherbyCityNameProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}
