if "%NET_FRAMEWORK_PB125%" == "" set NET_FRAMEWORK_PB125=%windir%\Microsoft.NET\Framework\v4.0.30319
%NET_FRAMEWORK_PB125%\csc
 if errorlevel 9009 exit 3
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.asmx" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.asmx"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.html" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.html"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.css" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.css"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.aspx" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.aspx"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.htm" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.htm"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.js" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.js"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.resx" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.resx"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\*.asax" del "D:\svn\QQOnline\online_webform.pbt_build\online\*.asax"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\build.bat" del "D:\svn\QQOnline\online_webform.pbt_build\online\build.bat"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\web.config" del "D:\svn\QQOnline\online_webform.pbt_build\online\web.config"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\bin" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\bin"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\images" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\images"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\scripts" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\scripts"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\temp" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\temp"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\Registry.xml" del "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\Registry.xml"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\a" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\a"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\b" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\b"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\c" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\c"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\d" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\d"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\e" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\e"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\f" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\f"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\g" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\g"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\h" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\h"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\i" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\i"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\j" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\j"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\k" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\k"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\l" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\l"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\m" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\m"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\n" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\n"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\o" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\o"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\p" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\p"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\q" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\q"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\r" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\r"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\s" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\s"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\t" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\t"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\u" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\u"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\v" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\v"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\w" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\w"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\x" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\x"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\y" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\y"
if exist "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\z" rd /s /q "D:\svn\QQOnline\online_webform.pbt_build\online\..\online_root\file\common\z"
rename "D:\svn\QQOnline\online_webform.pbt_build\online\AssemblyInfo.bak" "AssemblyInfo.cs"
"%PBNET_HOME%\bin\pb2cs" @"D:\svn\QQOnline\online_webform.pbt_build\projectinfo.txt"
if ERRORLEVEL 1 exit 1
call build.bat c- "D:\svn\QQOnline\online_webform.pbt_build\csc_output_file_name.txt"
if ERRORLEVEL 1 exit 2
