//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="n_serviceSoap", Namespace="http://tempurl.org")]
    public partial class n_service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback of_dbconnectOperationCompleted;
        
        /// <remarks/>
        public n_service() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["EndpointURL"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/hisserver/n_service.asmx";
            }
        }
        
        /// <remarks/>
        public event of_dbconnectCompletedEventHandler of_dbconnectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/of_dbconnect", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public short of_dbconnect(ref string as_message) {
            object[] results = this.Invoke("of_dbconnect", new object[] {
                        as_message});
            as_message = ((string)(results[1]));
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginof_dbconnect(string as_message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("of_dbconnect", new object[] {
                        as_message}, callback, asyncState);
        }
        
        /// <remarks/>
        public short Endof_dbconnect(System.IAsyncResult asyncResult, out string as_message) {
            object[] results = this.EndInvoke(asyncResult);
            as_message = ((string)(results[1]));
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void of_dbconnectAsync(string as_message) {
            this.of_dbconnectAsync(as_message, null);
        }
        
        /// <remarks/>
        public void of_dbconnectAsync(string as_message, object userState) {
            if ((this.of_dbconnectOperationCompleted == null)) {
                this.of_dbconnectOperationCompleted = new System.Threading.SendOrPostCallback(this.Onof_dbconnectOperationCompleted);
            }
            this.InvokeAsync("of_dbconnect", new object[] {
                        as_message}, this.of_dbconnectOperationCompleted, userState);
        }
        
        private void Onof_dbconnectOperationCompleted(object arg) {
            if ((this.of_dbconnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.of_dbconnectCompleted(this, new of_dbconnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void of_dbconnectCompletedEventHandler(object sender, of_dbconnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class of_dbconnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal of_dbconnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string as_message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}
